steps:
  - name: 'adoptopenjdk/openjdk8-openj9'
    args:
      - './gradlew'
      - 'build'
      - 'publish'
    env:
      - 'BUILD=$BUILD_ID'
      - 'PROJECT=$PROJECT_ID'
      - 'REPO=$REPO_NAME'
      - 'BRANCH=$BRANCH_NAME'
      - 'COMMIT=$SHORT_SHA'
    secretEnv:
      - 'AWS_ACCESS_KEY_ID'
      - 'AWS_SECRET_ACCESS_KEY'
secrets:
  - kmsKeyName: projects/hrznfactory/locations/global/keyRings/keyring/cryptoKeys/key
    secretEnv:
      AWS_ACCESS_KEY_ID: 'CiQA/t63gSsggo5nhDQZ72YFMY7sCwaN5dcdFN1G0xTyysDDsJISPQA2yBtTgGlgzgzZF3KqheWqQwzo5V6QVIcQd251vqR6yqA8DSHs/ynfG5wzLi3lmMAKaJ/2o7JJ0Bje68I='
      AWS_SECRET_ACCESS_KEY: 'CiQA/t63gdp6hjeEUm1CSZ/UJnHmx06Rq22D11nNZ0/O/QD+37sSUQA2yBtTzFyhuPUt/Ak0PrE3vzoDyEoMQQ04qNIldUNWUdLRVRpw39bG8SRa6opsZFs7pv2S/6hCoAZQ8CW5T1jueGrT0cdt3gtR35U9Uf8Rsg=='